[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs_20"]

[phases.install]
cmds = ["cd api && npm install --include=optional"]

[phases.build]
cmds = []

[start]
cmd = "cd api && node src/server.js"
