[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm rebuild better-sqlite3 --build-from-source"
]

[phases.build]
cmds = []

[start]
cmd = "node src/server.js"
